import { Router } from 'express';
import Groq from 'groq-sdk';
import PDFDocument from 'pdfkit';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { pool, query } from '../db/index.ts';
import { hashPassword } from '../db/password.ts';
import { AuthRequest, requireAuth, requireRole } from '../middleware/auth.ts';
import { Address, Rider } from '../../src/types.ts';

const router = Router();
const require = createRequire(resolve(process.cwd(), 'server/routes/riders.routes.ts'));
const pdfParse = require('pdf-parse') as (buffer: Buffer) => Promise<{ text: string; numpages: number }>;
const groqApiKey = process.env.GROQ_API_KEY?.trim();
const groq = groqApiKey ? new Groq({ apiKey: groqApiKey }) : null;
const maxCvBytes = 3 * 1024 * 1024;

function requireGroq() {
  if (!groq) {
    const error = new Error('AI CV assistance is unavailable. Please enter the information manually.');
    (error as Error & { statusCode?: number }).statusCode = 503;
    throw error;
  }
}

function decodePdf(value: unknown): Buffer {
  if (typeof value !== 'string') throw new Error('Upload a PDF CV to continue.');
  const base64 = value.replace(/^data:application\/pdf;base64,/, '');
  const buffer = Buffer.from(base64, 'base64');
  if (!buffer.length || buffer.length > maxCvBytes || buffer.subarray(0, 4).toString() !== '%PDF') {
    throw new Error('CV must be a valid PDF file under 3 MB.');
  }
  return buffer;
}

function parseJsonResponse(value: string): Record<string, unknown> {
  const start = value.indexOf('{');
  const end = value.lastIndexOf('}');
  if (start < 0 || end < start) throw new Error('AI returned an unreadable CV result. Please fill the fields manually.');
  return JSON.parse(value.slice(start, end + 1));
}

function cleanList(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string').map((item) => item.trim()).filter(Boolean).slice(0, 20) : [];
}

function hasMapCoordinates(address: any): boolean {
  return Number.isFinite(Number(address?.Latitude)) && Number(address.Latitude) >= -90 && Number(address.Latitude) <= 90 &&
    Number.isFinite(Number(address?.Longitude)) && Number(address.Longitude) >= -180 && Number(address.Longitude) <= 180;
}

function addressSignature(value: unknown): string {
  const address = typeof value === 'string' ? JSON.parse(value) : (value || {}) as Partial<Address>;
  const coordinate = (number: unknown) => number === null || number === undefined || number === '' || !Number.isFinite(Number(number)) ? null : Number(number);
  return JSON.stringify([
    address.House_Name || '', address.Street || '', address.City || '', address.Postal_Code || '',
    address.Additional_Info || '', coordinate(address.Latitude), coordinate(address.Longitude),
  ]);
}

function createRiderCvPdf(profile: { name: string; email: string; phone: string; presentAddress: Address; permanentAddress: Address; experience: string[]; previousJobs: string[]; education: string[] }): Promise<Buffer> {
  return new Promise((resolvePdf, reject) => {
    const document = new PDFDocument({ size: 'A4', margin: 54, info: { Title: `${profile.name} | ShopNiro Rider CV`, Author: 'ShopNiro' } });
    const chunks: Buffer[] = [];
    document.on('data', (chunk: Buffer) => chunks.push(chunk));
    document.on('end', () => resolvePdf(Buffer.concat(chunks)));
    document.on('error', reject);

    const pageWidth = 595.28;
    const left = 54;
    const contentWidth = 487;
    const right = left + contentWidth;
    const drawRunningHeader = () => {
      document.fillColor('#807653').font('Helvetica-Bold').fontSize(8).text('SHOPNIRO  /  RIDER PROFILE', left, 32, { characterSpacing: 0.8 });
      document.moveTo(left, 48).lineTo(right, 48).lineWidth(0.7).strokeColor('#e8e6df').stroke();
    };
    const drawFooter = () => {
      document.moveTo(left, 790).lineTo(right, 790).lineWidth(0.7).strokeColor('#e8e6df').stroke();
      document.fillColor('#858275').font('Helvetica').fontSize(8).text('Generated by ShopNiro Delivery Operations', left, 800);
      document.fillColor('#858275').font('Helvetica').fontSize(8).text('Professional profile', left, 800, { width: contentWidth, align: 'right' });
    };

    document.rect(0, 0, pageWidth, 166).fill('#10100f');
    document.rect(0, 162, pageWidth, 4).fill('#aaa17e');
    document.image(resolve(process.cwd(), 'ShopNiro-new-round-final.png'), left, 34, { fit: [56, 56] });
    document.fillColor('#ffffff').font('Times-Bold').fontSize(22).text('ShopNiro', 124, 39);
    document.fillColor('#c9c5b7').font('Helvetica').fontSize(9).text('MARKETPLACE  /  DELIVERY OPERATIONS', 125, 67, { characterSpacing: 0.7 });
    document.fillColor('#c9c5b7').font('Helvetica-Bold').fontSize(8).text('RIDER CURRICULUM VITAE', left, 101, { characterSpacing: 1.1 });
    document.fillColor('#ffffff').font('Times-Bold').fontSize(24).text(profile.name, left, 117, { width: contentWidth, height: 34, ellipsis: true });

    let y = 190;
    const nextPage = () => {
      drawFooter();
      document.addPage();
      drawRunningHeader();
      y = 66;
    };
    const addressText = (address: Address) => [address.House_Name, address.Street, address.City, address.Postal_Code]
      .filter(Boolean).join(', ') || 'Not provided';
    const section = (title: string, entries: string[]) => {
      if (!entries.length) return;
      if (y + 38 > 770) nextPage();
      document.fillColor('#807653').font('Helvetica-Bold').fontSize(9).text(title.toUpperCase(), left, y, { characterSpacing: 1 });
      y += 17;
      document.moveTo(left, y).lineTo(right, y).lineWidth(0.7).strokeColor('#e8e6df').stroke();
      y += 11;
      for (const entry of entries) {
        document.font('Helvetica').fontSize(10);
        const height = document.heightOfString(entry, { width: contentWidth - 17, lineGap: 3 });
        if (y + height > 770) nextPage();
        document.circle(left + 3, y + 6, 2).fill('#aaa17e');
        document.fillColor('#37362e').font('Helvetica').fontSize(10).text(entry, left + 14, y, { width: contentWidth - 17, lineGap: 3 });
        y += height + 8;
      }
      y += 9;
    };

    section('Contact', [profile.email, profile.phone]);
    section('Present address', [addressText(profile.presentAddress)]);
    section('Permanent address', [addressText(profile.permanentAddress)]);
    section('Relevant experience', profile.experience);
    section('Previous employment', profile.previousJobs);
    section('Education and qualifications', profile.education);
    drawFooter();
    document.end();
  });
}

const riderCvFileName = (name: string) => `${name.replace(/[^a-zA-Z0-9-_]+/g, '-').replace(/-+/g, '-').slice(0, 100) || 'rider'}-ShopNiro-CV.pdf`;

async function regenerateStoredRiderCv(riderId: string) {
  const result = await query(`
    SELECT r.name, r.number, r.present_address_json, r.permanent_address_json,
      r.experience_json, r.previous_jobs_json, r.education_json, u.email
    FROM riders r JOIN users u ON u.id = r.id WHERE r.id = $1
  `, [riderId]);
  if (!result.rows.length) return null;
  const row = result.rows[0];
  const address = (value: any): Address => typeof value === 'string' ? JSON.parse(value) : value || {};
  const fileName = riderCvFileName(String(row.name || 'Rider'));
  const buffer = await createRiderCvPdf({
    name: String(row.name || ''),
    email: String(row.email || ''),
    phone: String(row.number || ''),
    presentAddress: address(row.present_address_json),
    permanentAddress: address(row.permanent_address_json),
    experience: cleanList(row.experience_json),
    previousJobs: cleanList(row.previous_jobs_json),
    education: cleanList(row.education_json),
  });
  await query('UPDATE riders SET has_cv = TRUE, cv_file_name = $2, cv_pdf = $3 WHERE id = $1', [riderId, fileName, buffer]);
  return { fileName, buffer };
}

function mapRider(row: any): Rider {
  const points = Number(row.current_month_performance_points ?? row.performance_points);
  return {
    Rider_ID: row.id,
    Username: row.username || '',
    Name: row.name,
    Email: row.email || '',
    Number: row.number || '',
    Present_Address: row.present_address_json || {},
    Permanent_Address: row.permanent_address_json || {},
    Experience: cleanList(row.experience_json),
    Previous_Jobs: cleanList(row.previous_jobs_json),
    Education: cleanList(row.education_json),
    Status: row.status,
    Has_CV: Boolean(row.has_cv),
    CV_File_Name: row.cv_file_name || undefined,
    Current_Latitude: row.current_latitude === null ? undefined : Number(row.current_latitude),
    Current_Longitude: row.current_longitude === null ? undefined : Number(row.current_longitude),
    Total_Deliveries: Number(row.total_deliveries) || 0,
    Timely_Deliveries: Number(row.timely_deliveries) || 0,
    Late_Deliveries: Number(row.late_deliveries) || 0,
    Performance_Points: Number.isFinite(points) ? points : 100,
    Average_Rating: Number(row.average_rating) || 0,
    Wallet_Balance: Number(row.wallet_balance) || 0,
    Created_At: row.created_at ? new Date(row.created_at).toISOString() : new Date().toISOString(),
  };
}

router.post('/cv/parse', async (req, res) => {
  try {
    requireGroq();
    const pdfBuffer = decodePdf(req.body?.cvBase64);
    const pdf = await pdfParse(pdfBuffer);
    const text = pdf.text.replace(/\s+/g, ' ').trim().slice(0, 45000);
    if (text.length < 40) return res.status(422).json({ error: 'This PDF has no readable text. Please enter your work and education details manually.' });

    const aiResult = await groq!.chat.completions.create({
      model: process.env.GROQ_MODEL_FAST?.trim() || 'openai/gpt-oss-20b',
      temperature: 0.1,
      messages: [
        { role: 'system', content: 'Extract only facts explicitly present in the CV. Return one JSON object with string-array fields experience, previousJobs, and education. Use empty arrays for missing information. Do not infer facts.' },
        { role: 'user', content: text },
      ],
    });
    const parsed = parseJsonResponse(aiResult.choices[0]?.message?.content || '');
    const extracted = {
      experience: cleanList(parsed.experience),
      previousJobs: cleanList(parsed.previousJobs),
      education: cleanList(parsed.education),
    };
    const missingFields = Object.entries(extracted).filter(([, values]) => values.length === 0).map(([field]) => field);
    return res.json({ extracted, missingFields });
  } catch (error: any) {
    const statusCode = error?.statusCode || 400;
    return res.status(statusCode).json({ error: error.message || 'Could not read this CV.' });
  }
});

router.post('/cv/format', async (req, res) => {
  try {
    requireGroq();
    const { experience, previousJobs, education } = req.body ?? {};
    const response = await groq!.chat.completions.create({
      model: process.env.GROQ_MODEL_FAST?.trim() || 'openai/gpt-oss-20b',
      temperature: 0.2,
      messages: [
        { role: 'system', content: 'Organize the applicant-provided facts into clear, consistent CV bullet points. Do not add or infer facts. Return one JSON object with string-array fields experience, previousJobs, and education. Preserve empty arrays.' },
        { role: 'user', content: JSON.stringify({ experience, previousJobs, education }) },
      ],
    });
    const parsed = parseJsonResponse(response.choices[0]?.message?.content || '');
    return res.json({
      experience: cleanList(parsed.experience),
      previousJobs: cleanList(parsed.previousJobs),
      education: cleanList(parsed.education),
    });
  } catch (error: any) {
    const statusCode = error?.statusCode || 503;
    return res.status(statusCode).json({ error: error.message || 'Could not format the CV. You can continue with your manual details.' });
  }
});

router.post('/apply', async (req, res) => {
  const {
    Username,
    Name,
    Email,
    Password,
    Number: phone,
    Present_Address,
    Permanent_Address,
    Has_CV,
    CV_Base64,
    CV_File_Name,
    Experience,
    Previous_Jobs,
    Education,
  } = req.body ?? {};

  if (![Username, Name, Email, Password, phone].every((value) => typeof value === 'string' && value.trim())) {
    return res.status(400).json({ error: 'Name, username, email, password, and phone number are required.' });
  }
  if (String(Password).length < 8) return res.status(400).json({ error: 'Password must be at least 8 characters.' });
  if (typeof Has_CV !== 'boolean') {
    return res.status(400).json({ error: 'Choose whether you have a CV.' });
  }
  if (
    !Present_Address?.Street || !Present_Address?.City || !Permanent_Address?.Street || !Permanent_Address?.City ||
    !hasMapCoordinates(Present_Address) || !hasMapCoordinates(Permanent_Address)
  ) {
    return res.status(400).json({ error: 'Select map locations and complete both present and permanent addresses.' });
  }

  if (Has_CV && !CV_Base64) {
    return res.status(400).json({ error: 'Upload your PDF CV to continue.' });
  }
  if (Has_CV) {
    try {
      decodePdf(CV_Base64);
    } catch (error: any) {
      return res.status(400).json({ error: error.message });
    }
  }

  const experience = cleanList(Experience);
  const previousJobs = cleanList(Previous_Jobs);
  const education = cleanList(Education);
  let cvBuffer: Buffer;
  try {
    cvBuffer = await createRiderCvPdf({
      name: String(Name).trim(),
      email: String(Email).trim().toLowerCase(),
      phone: String(phone).trim(),
      presentAddress: Present_Address as Address,
      permanentAddress: Permanent_Address as Address,
      experience,
      previousJobs,
      education,
    });
  } catch (error) {
    console.error('Could not generate rider CV PDF:', error);
    return res.status(500).json({ error: 'Could not generate your rider CV PDF. Please try again.' });
  }
  const cvFileName = `${String(Name).trim().replace(/[^a-zA-Z0-9-_]+/g, '-').replace(/-+/g, '-').slice(0, 100) || 'rider'}-ShopNiro-CV.pdf`;

  const client = await pool.connect();
  try {
    const riderId = `RDR-${Date.now()}-${Math.floor(1000 + Math.random() * 9000)}`;
    const username = String(Username).trim().toLowerCase();
    const email = String(Email).trim().toLowerCase();
    await client.query('BEGIN');
    const duplicate = await client.query(
      'SELECT 1 FROM users WHERE lower(email) = $1 OR lower(username) = $2 LIMIT 1',
      [email, username]
    );
    if (duplicate.rows.length) {
      await client.query('ROLLBACK');
      return res.status(409).json({ error: 'That email or username is already registered.' });
    }
    await client.query(
      'INSERT INTO users (id, username, password, email, role) VALUES ($1, $2, $3, $4, $5)',
      [riderId, username, await hashPassword(String(Password)), email, 'rider']
    );
    await client.query(
      `INSERT INTO riders (
        id, name, number, status, present_address_json, permanent_address_json,
        has_cv, cv_file_name, cv_pdf, experience_json, previous_jobs_json, education_json
      ) VALUES ($1, $2, $3, 'pending', $4::jsonb, $5::jsonb, $6, $7, $8, $9::jsonb, $10::jsonb, $11::jsonb)`,
      [
        riderId,
        String(Name).trim(),
        String(phone).trim(),
        JSON.stringify(Present_Address as Address),
        JSON.stringify(Permanent_Address as Address),
        true,
        cvFileName,
        cvBuffer,
        JSON.stringify(experience),
        JSON.stringify(previousJobs),
        JSON.stringify(education),
      ]
    );
    await client.query('COMMIT');
    return res.status(201).json({ success: true, status: 'pending', message: 'Application received. Your ShopNiro CV PDF has been generated and saved. An administrator must approve your rider account before delivery operations are available.' });
  } catch (error: any) {
    await client.query('ROLLBACK');
    console.error('Rider application failed:', error);
    return res.status(500).json({ error: 'Could not submit rider application.' });
  } finally {
    client.release();
  }
});

router.get('/applications', requireAuth, requireRole(['admin']), async (_req, res) => {
  try {
    const result = await query(`
      SELECT r.*, u.username, u.email
      FROM riders r JOIN users u ON u.id = r.id
      ORDER BY CASE WHEN r.status = 'pending' THEN 0 ELSE 1 END, r.created_at DESC
    `);
    res.json(result.rows.map(mapRider));
  } catch (error: any) {
    console.error('Failed to load rider applications:', error);
    res.status(500).json({ error: 'Failed to load rider applications.' });
  }
});

router.get('/applications/:id/cv', requireAuth, requireRole(['admin']), async (req, res) => {
  try {
    const cv = await regenerateStoredRiderCv(req.params.id);
    if (!cv) return res.status(404).json({ error: 'CV not found.' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${cv.fileName.replace(/[\r\n"]+/g, '')}"`);
    return res.send(cv.buffer);
  } catch (error: any) {
    console.error('Failed to fetch rider CV:', error);
    return res.status(500).json({ error: 'Failed to fetch CV.' });
  }
});

router.patch('/applications/:id/status', requireAuth, requireRole(['admin']), async (req, res) => {
  const { status } = req.body ?? {};
  if (!['approved', 'rejected', 'suspended'].includes(status)) {
    return res.status(400).json({ error: 'Choose approved, rejected, or suspended.' });
  }
  try {
    const result = await query(
      'UPDATE riders SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, status',
      [req.params.id, status]
    );
    if (!result.rows.length) return res.status(404).json({ error: 'Rider application not found.' });
    return res.json({ Rider_ID: result.rows[0].id, Status: result.rows[0].status });
  } catch (error: any) {
    console.error('Failed to update rider application:', error);
    return res.status(500).json({ error: 'Failed to update rider application.' });
  }
});

router.get('/me', requireAuth, requireRole(['rider']), async (req: AuthRequest, res) => {
  try {
    const riderId = req.user!.entityId;
    const result = await query(`
      WITH delivery_totals AS (
        SELECT COUNT(*)::integer AS total_deliveries,
          COUNT(*) FILTER (WHERE COALESCE(rd.was_timely, rd.delivered_at <= rd.due_at, FALSE))::integer AS timely_deliveries,
          COUNT(*) FILTER (WHERE NOT COALESCE(rd.was_timely, rd.delivered_at <= rd.due_at, FALSE))::integer AS late_deliveries,
          COALESCE(SUM(rd.cod_amount) FILTER (WHERE rd.cod_collected AND rd.cod_amount > 0), 0) AS cod_deductions
        FROM rider_deliveries rd
        WHERE rd.rider_id = $1 AND rd.status = 'delivered'
          AND rd.delivered_at >= date_trunc('month', CURRENT_DATE)
          AND rd.delivered_at < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month'
      ), previous_salary AS (
        SELECT totals.*,
          COALESCE(score.performance_points, 100) AS previous_points,
          COALESCE(score.salary_base_amount,
            NULLIF(score.salary_amount + score.cod_deductions - score.delivery_pay_amount - score.perfect_month_bonus, 0),
            30000) AS previous_salary_base
        FROM delivery_totals totals
        LEFT JOIN rider_monthly_scores score ON score.rider_id = $1
          AND score.month_start = date_trunc('month', CURRENT_DATE)::date
      ), scored AS (
        SELECT previous_salary.*,
          GREATEST(0, 100 - LEAST(late_deliveries, 5) - GREATEST(late_deliveries - 5, 0) * 6) AS points
        FROM previous_salary
      ), monthly_score AS (
        INSERT INTO rider_monthly_scores (
          rider_id, month_start, performance_points, total_deliveries,
          timely_deliveries, late_deliveries, salary_amount, salary_base_amount,
          delivery_pay_amount, perfect_month_bonus, cod_deductions, salary_available_at
        )
        SELECT $1, date_trunc('month', CURRENT_DATE)::date, points,
          total_deliveries, timely_deliveries, late_deliveries,
          GREATEST(0, ROUND(previous_salary_base * (1 + (points - previous_points) / 100.0) +
            total_deliveries * 50 + CASE WHEN total_deliveries > 0 AND late_deliveries = 0 THEN 10000 ELSE 0 END - cod_deductions, 2)),
          ROUND(previous_salary_base * (1 + (points - previous_points) / 100.0), 2),
          total_deliveries * 50,
          CASE WHEN total_deliveries > 0 AND late_deliveries = 0 THEN 10000 ELSE 0 END,
          cod_deductions,
          date_trunc('month', CURRENT_DATE)::date + INTERVAL '1 month 29 days'
        FROM scored
        ON CONFLICT (rider_id, month_start) DO UPDATE SET
          performance_points = EXCLUDED.performance_points,
          total_deliveries = EXCLUDED.total_deliveries,
          timely_deliveries = EXCLUDED.timely_deliveries,
          late_deliveries = EXCLUDED.late_deliveries,
          salary_amount = EXCLUDED.salary_amount,
          salary_base_amount = EXCLUDED.salary_base_amount,
          delivery_pay_amount = EXCLUDED.delivery_pay_amount,
          perfect_month_bonus = EXCLUDED.perfect_month_bonus,
          cod_deductions = EXCLUDED.cod_deductions,
          salary_available_at = EXCLUDED.salary_available_at
        RETURNING performance_points
      )
      SELECT r.*, u.username, u.email,
        COALESCE((SELECT AVG(rr.rating) FROM rider_reviews rr WHERE rr.rider_id = r.id), 0) AS average_rating,
        monthly_score.performance_points AS current_month_performance_points
      FROM riders r JOIN users u ON u.id = r.id
      CROSS JOIN monthly_score
      WHERE r.id = $1
    `, [riderId]);
    if (!result.rows.length) return res.status(404).json({ error: 'Rider profile not found.' });
    return res.json(mapRider(result.rows[0]));
  } catch (error: any) {
    console.error('Failed to load rider profile:', error);
    return res.status(500).json({ error: 'Failed to load rider profile.' });
  }
});

router.get('/me/cv', requireAuth, requireRole(['rider']), async (req: AuthRequest, res) => {
  try {
    const cv = await regenerateStoredRiderCv(req.user!.entityId);
    if (!cv) return res.status(404).json({ error: 'Rider CV not found.' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${cv.fileName.replace(/[\r\n"]+/g, '')}"`);
    return res.send(cv.buffer);
  } catch (error: any) {
    console.error('Could not prepare rider CV preview:', error);
    return res.status(500).json({ error: 'Could not prepare your CV preview.' });
  }
});

router.put('/me', requireAuth, requireRole(['rider']), async (req: AuthRequest, res) => {
  const {
    Username,
    Name,
    Email,
    Password,
    Number: phone,
    Present_Address,
    Permanent_Address,
    Experience,
    Previous_Jobs,
    Education,
  } = req.body ?? {};

  if (![Username, Name, Email, phone].every((value) => typeof value === 'string' && value.trim()) || !String(Email).includes('@')) {
    return res.status(400).json({ error: 'Name, username, email, and phone number are required.' });
  }
  if (Password !== undefined && Password !== '' && (typeof Password !== 'string' || Password.length < 8)) {
    return res.status(400).json({ error: 'A new password must be at least 8 characters.' });
  }
  if (
    !Present_Address?.Street || !Present_Address?.City || !Permanent_Address?.Street || !Permanent_Address?.City ||
    !hasMapCoordinates(Present_Address) || !hasMapCoordinates(Permanent_Address)
  ) {
    return res.status(400).json({ error: 'Select map locations and complete both present and permanent addresses.' });
  }

  const riderId = req.user!.entityId;
  const username = String(Username).trim().toLowerCase();
  const email = String(Email).trim().toLowerCase();
  const experience = cleanList(Experience);
  const previousJobs = cleanList(Previous_Jobs);
  const education = cleanList(Education);
  const cvFileName = `${String(Name).trim().replace(/[^a-zA-Z0-9-_]+/g, '-').replace(/-+/g, '-').slice(0, 100) || 'rider'}-ShopNiro-CV.pdf`;

  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const currentResult = await client.query(`
      SELECT r.*, u.username, u.email,
        COALESCE((SELECT AVG(rr.rating) FROM rider_reviews rr WHERE rr.rider_id = r.id), 0) AS average_rating,
        COALESCE(ms.performance_points, 100) AS current_month_performance_points
      FROM riders r JOIN users u ON u.id = r.id
      LEFT JOIN rider_monthly_scores ms ON ms.rider_id = r.id
        AND ms.month_start = date_trunc('month', CURRENT_DATE)::date
      WHERE r.id = $1
      FOR UPDATE OF r, u
    `, [riderId]);
    if (!currentResult.rows.length) {
      await client.query('ROLLBACK');
      return res.status(404).json({ error: 'Rider profile not found.' });
    }
    const current = currentResult.rows[0];
    const profileChanged =
      String(current.username || '').toLowerCase() !== username ||
      String(current.email || '').toLowerCase() !== email ||
      String(current.name || '') !== String(Name).trim() ||
      String(current.number || '') !== String(phone).trim() ||
      addressSignature(current.present_address_json) !== addressSignature(Present_Address) ||
      addressSignature(current.permanent_address_json) !== addressSignature(Permanent_Address) ||
      JSON.stringify(cleanList(current.experience_json)) !== JSON.stringify(experience) ||
      JSON.stringify(cleanList(current.previous_jobs_json)) !== JSON.stringify(previousJobs) ||
      JSON.stringify(cleanList(current.education_json)) !== JSON.stringify(education);
    const passwordChanged = typeof Password === 'string' && Password.length > 0;
    if (!profileChanged && !passwordChanged) {
      await client.query('COMMIT');
      return res.json(mapRider(current));
    }

    const duplicate = await client.query(
      'SELECT 1 FROM users WHERE id <> $3 AND (lower(email) = $1 OR lower(username) = $2) LIMIT 1',
      [email, username, riderId]
    );
    if (duplicate.rows.length) {
      await client.query('ROLLBACK');
      return res.status(409).json({ error: 'That email or username is already registered.' });
    }
    const passwordHash = passwordChanged ? await hashPassword(String(Password)) : null;
    await client.query(
      'UPDATE users SET username = $2, email = $3, password = COALESCE($4, password) WHERE id = $1',
      [riderId, username, email, passwordHash]
    );
    if (profileChanged) {
      const cvBuffer = await createRiderCvPdf({
        name: String(Name).trim(),
        email,
        phone: String(phone).trim(),
        presentAddress: Present_Address as Address,
        permanentAddress: Permanent_Address as Address,
        experience,
        previousJobs,
        education,
      });
      await client.query(`
        UPDATE riders SET name = $2, number = $3, present_address_json = $4::jsonb,
          permanent_address_json = $5::jsonb, experience_json = $6::jsonb,
          previous_jobs_json = $7::jsonb, education_json = $8::jsonb,
          has_cv = TRUE, cv_file_name = $9, cv_pdf = $10, status = 'pending',
          updated_at = CURRENT_TIMESTAMP
        WHERE id = $1
      `, [
        riderId,
        String(Name).trim(),
        String(phone).trim(),
        JSON.stringify(Present_Address as Address),
        JSON.stringify(Permanent_Address as Address),
        JSON.stringify(experience),
        JSON.stringify(previousJobs),
        JSON.stringify(education),
        cvFileName,
        cvBuffer,
      ]);
    }
    const result = await client.query(`
      SELECT r.*, u.username, u.email,
        COALESCE((SELECT AVG(rr.rating) FROM rider_reviews rr WHERE rr.rider_id = r.id), 0) AS average_rating,
        COALESCE(ms.performance_points, 100) AS current_month_performance_points
      FROM riders r JOIN users u ON u.id = r.id
      LEFT JOIN rider_monthly_scores ms ON ms.rider_id = r.id
        AND ms.month_start = date_trunc('month', CURRENT_DATE)::date
      WHERE r.id = $1
    `, [riderId]);
    await client.query('COMMIT');
    return res.json(mapRider(result.rows[0]));
  } catch (error: any) {
    await client.query('ROLLBACK');
    if (error?.code === '23505') return res.status(409).json({ error: 'That email or username is already registered.' });
    console.error('Could not update rider profile:', error);
    return res.status(500).json({ error: 'Could not update your rider details.' });
  } finally {
    client.release();
  }
});

export default router;